# Generated by Django 4.2.1 on 2023-05-26 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9fa1fec-3d25-4635-b813-16396e2ff881'), primary_key=True, serialize=False),
        ),
    ]
