# Generated by Django 4.2.1 on 2023-05-26 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='addition_to_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('196b60a6-683f-4838-9ae6-69fec8feda13'), primary_key=True, serialize=False),
        ),
    ]
