# Generated by Django 4.2.1 on 2023-05-26 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productformainpage_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15c38ce0-461b-432e-b071-4bdd7846472a'), primary_key=True, serialize=False),
        ),
    ]
