# Generated by Django 4.2.1 on 2023-05-26 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b8aee69-5280-4172-a7cf-3c1b3144ec84'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
