# Generated by Django 4.2.1 on 2023-05-26 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cart_id_alter_categories_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4fe5048e-95ed-492c-8e1d-c7853fc0a760'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
