# Generated by Django 4.2.1 on 2023-05-27 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('890c1501-5349-4a95-a1ee-f7413e4df6a2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='main/static/main/img'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(upload_to='img', verbose_name='img'),
        ),
    ]
