# Generated by Django 4.2.1 on 2023-05-28 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cart_id_alter_product_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='aboba-main-category', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='aboba-product', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(default='aboba-sub', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('890f0fac-97f6-4029-8e14-a912f588cd35'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
