# Generated by Django 4.2.1 on 2023-05-28 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cart_id_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('33a6d79b-8bd5-485f-8cdc-3ae7c137c698'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
