# Generated by Django 4.2.1 on 2023-05-28 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cart_id_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f128a770-b0aa-42bf-ba55-2cf83d530fdc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
