# Generated by Django 4.2.1 on 2023-05-28 19:30

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('myapp', 'MyModel')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_cart_id_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88ee5ef3-9656-4f90-afdd-985e6e9ca11e'), primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=uuid.UUID('34c50ffa-1691-4ac5-935b-0925b1c9ed89'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6440b4e9-f1a7-4d8a-8b23-b69779e04cfa'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3ccd186e-b4e4-4fac-bf3a-f69273b100cd'), max_length=100, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
