# Generated by Django 4.2.1 on 2023-05-29 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8aab1dc1-de38-4a7d-9300-62ef2b71d870'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to='main/static/main/img'),
        ),
    ]
