# Generated by Django 4.2.1 on 2023-05-28 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_cart_id_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3dc650f6-1293-448a-8ac9-0c6baa7adcd1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to='main/static/main/img', verbose_name='img'),
        ),
    ]
